$f = "C:\Users\machintosh\Documents\files\Grayfix1\contracts\grayfix_escrow\tests\dispute_flow.rs"
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add('extern crate std;')
$lines.Add('use grayfix_escrow::{DataKey, EscrowContract, EscrowContractClient, TradeStatus};')
$lines.Add('use soroban_sdk::{')
$lines.Add('    contract, contractimpl, contracttype,')
$lines.Add('    testutils::{Address as _, Ledger},')
$lines.Add('    Address, Env, String as SorobanString, Symbol, symbol_short,')
$lines.Add('};')
$lines.Add('use std::cell::RefCell;')
$lines.Add('use std::collections::HashMap;')
$lines.Add('use std::string::String;')
$lines.Add('use std::vec::Vec;')
$lines.Add('')
$lines.Add('const STATIC_CID: &str = "QmTest123456789abcdefghijklmnopqrstuvwxyz";')
$lines.Add('thread_local! {')
$lines.Add('    static MOCK_IPFS: RefCell<HashMap<u64, String>> = RefCell::new(HashMap::new());')
$lines.Add('}')
$lines.Add('fn ipfs_upload(_d: &[u8], id: u64) -> String {')
$lines.Add('    MOCK_IPFS.with(|m| m.borrow_mut().insert(id, STATIC_CID.to_string()));')
$lines.Add('    STATIC_CID.to_string()')
$lines.Add('}')
$lines.Add('fn ipfs_get(id: u64) -> Option<String> { MOCK_IPFS.with(|m| m.borrow().get(&id).cloned()) }')
$lines.Add('fn ipfs_reset() { MOCK_IPFS.with(|m| m.borrow_mut().clear()); }')

$lines.Add('')
$lines.Add('#[contract] pub struct MockToken;')
$lines.Add('#[contracttype] #[derive(Clone)] pub enum MTKey { Balance(Address) }')
$lines.Add('#[contractimpl] impl MockToken {')
$lines.Add('    pub fn mint(env: Env, to: Address, amount: i128) {')
$lines.Add('        let k = MTKey::Balance(to);')
$lines.Add('        let c: i128 = env.storage().persistent().get(&k).unwrap_or(0);')
$lines.Add('        env.storage().persistent().set(&k, &(c + amount));')
$lines.Add('    }')
$lines.Add('    pub fn balance(env: Env, id: Address) -> i128 {')
$lines.Add('        env.storage().persistent().get(&MTKey::Balance(id)).unwrap_or(0)')
$lines.Add('    }')
$lines.Add('    pub fn transfer(env: Env, from: Address, to: Address, amount: i128) {')
$lines.Add('        let fk = MTKey::Balance(from); let tk = MTKey::Balance(to);')
$lines.Add('        let fb: i128 = env.storage().persistent().get(&fk).unwrap_or(0);')
$lines.Add('        assert!(fb >= amount, "insufficient balance");')
$lines.Add('        let tb: i128 = env.storage().persistent().get(&tk).unwrap_or(0);')
$lines.Add('        env.storage().persistent().set(&fk, &(fb - amount));')
$lines.Add('        env.storage().persistent().set(&tk, &(tb + amount));')
$lines.Add('    }')
$lines.Add('}')

$lines.Add('')
$lines.Add('#[derive(Clone, Debug, PartialEq)] enum DbStatus { Funded, Disputed, Cancelled }')
$lines.Add('#[derive(Clone, Debug)]')
$lines.Add('struct DbTrade { trade_id: u64, amount_usdc: i128, status: DbStatus, evidence_cid: Option<String> }')
$lines.Add('thread_local! { static MOCK_DB: RefCell<HashMap<u64, DbTrade>> = RefCell::new(HashMap::new()); }')
$lines.Add('fn db_upsert(t: DbTrade) { MOCK_DB.with(|db| { db.borrow_mut().insert(t.trade_id, t); }); }')
$lines.Add('fn db_get(id: u64) -> Option<DbTrade> { MOCK_DB.with(|db| db.borrow().get(&id).cloned()) }')
$lines.Add('fn db_reset() { MOCK_DB.with(|db| db.borrow_mut().clear()); }')
$lines.Add('fn backend_on_dispute(id: u64) {')
$lines.Add('    MOCK_DB.with(|db| { if let Some(t) = db.borrow_mut().get_mut(&id) { t.status = DbStatus::Disputed; } });')
$lines.Add('}')
$lines.Add('fn backend_on_resolved(id: u64) {')
$lines.Add('    MOCK_DB.with(|db| { if let Some(t) = db.borrow_mut().get_mut(&id) { t.status = DbStatus::Cancelled; } });')
$lines.Add('}')
$lines.Add('fn backend_store_cid(id: u64, cid: &str) {')
$lines.Add('    MOCK_DB.with(|db| { if let Some(t) = db.borrow_mut().get_mut(&id) { t.evidence_cid = Some(cid.to_string()); } });')
$lines.Add('}')

$lines.Add('')
$lines.Add('struct H { env: Env, escrow: Address, token: Address, admin: Address, buyer: Address, seller: Address, unrelated: Address }')
$lines.Add('impl H {')
$lines.Add('    fn new() -> Self {')
$lines.Add('        let env = Env::default(); env.mock_all_auths();')
$lines.Add('        env.ledger().with_mut(|l| { l.timestamp = 1_700_000_000; l.sequence_number = 100; });')
$lines.Add('        let escrow = env.register(EscrowContract, ()); let token = env.register(MockToken, ());')
$lines.Add('        let admin = Address::generate(&env); let buyer = Address::generate(&env);')
$lines.Add('        let seller = Address::generate(&env); let unrelated = Address::generate(&env);')
$lines.Add('        H { env, escrow, token, admin, buyer, seller, unrelated }')
$lines.Add('    }')
$lines.Add('    fn c(&self) -> EscrowContractClient { EscrowContractClient::new(&self.env, &self.escrow) }')
$lines.Add('    fn tok(&self) -> MockTokenClient { MockTokenClient::new(&self.env, &self.token) }')
$lines.Add('    fn funded_trade(&self, amount: i128) -> u64 {')
$lines.Add('        self.c().initialize(&self.admin, &self.token, &0u32);')
$lines.Add('        self.tok().mint(&self.escrow, &amount);')
$lines.Add('        let id = self.c().create_trade(&self.buyer, &self.seller, &amount);')
$lines.Add('        self.c().mark_funded(&id);')
$lines.Add('        db_upsert(DbTrade { trade_id: id, amount_usdc: amount, status: DbStatus::Funded, evidence_cid: None });')
$lines.Add('        id')
$lines.Add('    }')
$lines.Add('    fn cleanup(&self) { ipfs_reset(); db_reset(); }')
$lines.Add('}')
$lines.Add('fn has_event(env: &Env, sym: Symbol) -> bool {')
$lines.Add('    env.events().all().iter().any(|e| e.0.len() >= 1 && { let s: Symbol = e.0.get(0).unwrap(); s == sym })')
$lines.Add('}')

$lines.Add('')
$lines.Add('// ── Test 1: Evidence happy path ─────────────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_evidence_stores_cid_on_chain_and_in_db() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    let dummy: Vec<u8> = vec![0u8; 5 * 1024 * 1024];')
$lines.Add('    let cid = ipfs_upload(&dummy, id);')
$lines.Add('    assert_eq!(cid, STATIC_CID);')
$lines.Add('    let scid = SorobanString::from_str(&h.env, &cid);')
$lines.Add('    h.c().submit_evidence(&id, &scid, &h.buyer);')
$lines.Add('    backend_store_cid(id, &cid);')
$lines.Add('    assert_eq!(db_get(id).unwrap().evidence_cid.as_deref(), Some(STATIC_CID));')
$lines.Add('    let ev = h.c().get_evidence(&id);')
$lines.Add('    assert_eq!(ev.cid, scid); assert_eq!(ev.submitter, h.buyer);')
$lines.Add('    h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 2: Evidence 403 ─────────────────────────────────────────────────────')
$lines.Add('#[test] #[should_panic(expected = "Unauthorized: only buyer or seller can submit evidence")]')
$lines.Add('fn test_evidence_rejects_unrelated_user() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    h.c().submit_evidence(&id, &SorobanString::from_str(&h.env, STATIC_CID), &h.unrelated);')
$lines.Add('    h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 3: Evidence immutability (405) ─────────────────────────────────────')
$lines.Add('#[test] #[should_panic(expected = "EvidenceImmutable: evidence already submitted")]')
$lines.Add('fn test_evidence_overwrite_rejected() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    let cid = SorobanString::from_str(&h.env, STATIC_CID);')
$lines.Add('    h.c().submit_evidence(&id, &cid, &h.buyer);')
$lines.Add('    h.c().submit_evidence(&id, &SorobanString::from_str(&h.env, "QmDifferentCID"), &h.buyer);')
$lines.Add('    h.cleanup();')
$lines.Add('}')

$lines.Add('')
$lines.Add('// ── Test 4: Dispute initiation ───────────────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_dispute_initiation_event_and_db_sync() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer);')
$lines.Add('    assert_eq!(h.c().get_trade(&id).status, TradeStatus::Disputed);')
$lines.Add('    assert!(has_event(&h.env, symbol_short!("TRDDISP")), "TradeDisputed event missing");')
$lines.Add('    backend_on_dispute(id);')
$lines.Add('    assert_eq!(db_get(id).unwrap().status, DbStatus::Disputed);')
$lines.Add('    h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 5: State lock ───────────────────────────────────────────────────────')
$lines.Add('#[test] #[should_panic(expected = "cannot deliver while trade is disputed")]')
$lines.Add('fn test_deliver_item_blocked_during_dispute() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer);')
$lines.Add('    h.c().deliver_item(&id);')
$lines.Add('    h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 6: Mediator sees streaming URL ──────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_mediator_sees_streaming_url() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    let cid = ipfs_upload(&[0u8; 1024], id);')
$lines.Add('    h.c().submit_evidence(&id, &SorobanString::from_str(&h.env, &cid), &h.buyer);')
$lines.Add('    backend_store_cid(id, &cid);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer);')
$lines.Add('    backend_on_dispute(id);')
$lines.Add('    let db = db_get(id).unwrap();')
$lines.Add('    assert_eq!(db.status, DbStatus::Disputed);')
$lines.Add('    let url = std::format!("https://ipfs.io/ipfs/{}", db.evidence_cid.unwrap());')
$lines.Add('    assert!(url.contains(STATIC_CID));')
$lines.Add('    assert!(url.starts_with("https://ipfs.io/ipfs/"));')
$lines.Add('    assert_eq!(ipfs_get(id).as_deref(), Some(STATIC_CID));')
$lines.Add('    h.cleanup();')
$lines.Add('}')

$lines.Add('')
$lines.Add('// ── Test 7: 30/70 split ──────────────────────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_resolve_30_70_split_exact_balances() {')
$lines.Add('    let h = H::new(); let amount: i128 = 100_000_000; let id = h.funded_trade(amount);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer);')
$lines.Add('    h.c().resolve_dispute(&id, &3_000u32);')
$lines.Add('    assert!(has_event(&h.env, symbol_short!("TRDRES")), "TradeResolved event missing");')
$lines.Add('    let expected_seller: i128 = amount * 3_000 / 10_000;')
$lines.Add('    let expected_buyer:  i128 = amount - expected_seller;')
$lines.Add('    assert_eq!(h.tok().balance(&h.seller), expected_seller, "seller must receive 30 USDC");')
$lines.Add('    assert_eq!(h.tok().balance(&h.buyer),  expected_buyer,  "buyer must receive 70 USDC");')
$lines.Add('    assert_eq!(h.tok().balance(&h.escrow), 0, "escrow must be drained");')
$lines.Add('    assert_eq!(h.c().get_trade(&id).status, TradeStatus::Cancelled);')
$lines.Add('    backend_on_resolved(id);')
$lines.Add('    assert_eq!(db_get(id).unwrap().status, DbStatus::Cancelled);')
$lines.Add('    h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 8: 100% seller ──────────────────────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_resolve_full_seller_payout() {')
$lines.Add('    let h = H::new(); let amount: i128 = 100_000_000; let id = h.funded_trade(amount);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer); h.c().resolve_dispute(&id, &10_000u32);')
$lines.Add('    assert_eq!(h.tok().balance(&h.seller), amount);')
$lines.Add('    assert_eq!(h.tok().balance(&h.buyer), 0);')
$lines.Add('    assert_eq!(h.tok().balance(&h.escrow), 0);')
$lines.Add('    h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 9: 100% buyer ───────────────────────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_resolve_full_buyer_refund() {')
$lines.Add('    let h = H::new(); let amount: i128 = 100_000_000; let id = h.funded_trade(amount);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer); h.c().resolve_dispute(&id, &0u32);')
$lines.Add('    assert_eq!(h.tok().balance(&h.buyer), amount);')
$lines.Add('    assert_eq!(h.tok().balance(&h.seller), 0);')
$lines.Add('    assert_eq!(h.tok().balance(&h.escrow), 0);')
$lines.Add('    h.cleanup();')
$lines.Add('}')

$lines.Add('')
$lines.Add('// ── Test 10: Resolve non-disputed ───────────────────────────────────────────')
$lines.Add('#[test] #[should_panic(expected = "trade must be in Disputed status")]')
$lines.Add('fn test_resolve_fails_on_non_disputed_trade() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    h.c().resolve_dispute(&id, &5_000u32); h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 11: Invalid bps ─────────────────────────────────────────────────────')
$lines.Add('#[test] #[should_panic(expected = "seller_gets_bps must be <= 10000")]')
$lines.Add('fn test_resolve_rejects_invalid_bps() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer);')
$lines.Add('    h.c().resolve_dispute(&id, &10_001u32); h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 12: Dispute completed trade ────────────────────────────────────────')
$lines.Add('#[test] #[should_panic(expected = "can only dispute a Funded or Delivered trade")]')
$lines.Add('fn test_dispute_fails_on_completed_trade() {')
$lines.Add('    let h = H::new(); let id = h.funded_trade(100_000_000);')
$lines.Add('    h.c().confirm_delivery(&id); h.c().release_funds(&id);')
$lines.Add('    h.c().initiate_dispute(&id, &h.buyer); h.cleanup();')
$lines.Add('}')
$lines.Add('')
$lines.Add('// ── Test 13: Mock state cleanup ──────────────────────────────────────────────')
$lines.Add('#[test]')
$lines.Add('fn test_mock_state_wiped_after_cleanup() {')
$lines.Add('    ipfs_upload(&[1u8], 999);')
$lines.Add('    db_upsert(DbTrade { trade_id: 999, amount_usdc: 1, status: DbStatus::Funded, evidence_cid: None });')
$lines.Add('    ipfs_reset(); db_reset();')
$lines.Add('    assert!(ipfs_get(999).is_none(), "IPFS state must be wiped");')
$lines.Add('    assert!(db_get(999).is_none(), "DB state must be wiped");')
$lines.Add('}')

[System.IO.File]::WriteAllLines($f, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "wrote:$((Get-Item $f).Length)"
