apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grayfix-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - "grayfixvault.com"
        - "www.grayfixvault.com"
        - "api.grayfixvault.com"
      secretName: grayfixvault-tls
  rules:
    - host: "grayfixvault.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: "www.grayfixvault.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: "api.grayfixvault.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 4000
